services:
  smb35server-docker:
    container_name: smb35server-docker
    image: smb35server-docker:test
    environment:
      PUID: 1000
      GUID: 1000
      SERVER_ADDRESS: myveryownsmbserver.com
    hostname: smb35server-docker
    ports:
      - 20000:20000
      - 20001:20001
      - 20002:20002
    restart: unless-stopped