services:
  smb35server-docker:
    container_name: smb35server-docker
    image: ghcr.io/royaltongue/smb35server-docker:test
    environment:
      PUID: 1000 # Optional
      GUID: 1000 # Optional
      SERVER_ADDRESS: myveryownsmbserver.com # Not used yet
    hostname: smb35server-docker
    ports:
      - 20000:20000
      - 20001:20001
      - 20002:20002
    restart: unless-stopped